### ISSUE TITLE
Does v3.0.0 have released already?

### ISSUE THREAD

**Issue by ccqpein** [Frechmatz/cl-threadpool#2]
Hi, I am trying to use cl-threadpool to develop. I find the examples on the webpage cannot work. Specifically, it gives me `TEXT: "Cannot add job to thread pool that hasn't been started: Example thread pool"` condition.

I check the changelog and figure out `Removed cl-threadpool:start` in version 3.0.0. However, the version on quicklisp still 2.0.0. 

Has 3.0.0 version already released?

Thank you

**Comment by Frechmatz** [comment]
Hi there,

thank you for trying out cl-threadpool 😃 

The examples on the webpage are for version 3.0.0 of the library. A moment ago i've merged this version into the release branch of Quicklisp. So with the next Quicklisp update the latest version should be available.

In order to try out the examples, you may clone the project:

Clone:

> cd ~/quicklisp/local-projects
> git clone https://github.com/Frechmatz/cl-threadpool.git

Load project and install dependencies (inside Repl). 

> (ql:quickload :cl-threadpool)

This should do the job and the system should now be loadable via 

>  (asdf:load-system :cl-threadpool) 

I'll update this issue when version 3.0.0 has been released. Please come back to me if you experience any problems.

Thanks,
Oliver

**Comment by ccqpein** [comment]
Sure! It is a nice tool, thanks for your work.

**Comment by Frechmatz** [comment]
Hi there, version 3.0.0 has been released.
